print("Comment tu t'appelles?")
prenom = input()
print(prenom)
print("Quel age as-tu")
age = input()
print(age)
print("Où habites-tu")
ville = input()
print(ville)
print("Bonjour " + prenom + " tu as " + age + " et tu habites à " + ville)